# hereliesaz/reup/ReUp-c714b8692ef249c9d91ed57a33a63f43f5c8c59d/gradle/gradle-daemon-jvm.properties

# Hardcoded API URLs excised due to 400 Bad Request link rot.
# We will rely on the Foojay resolver plugin to dynamically locate the toolchain.
toolchainVendor=JETBRAINS
toolchainVersion=21
